import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import WebcamCapture from '@/components/WebcamCapture'
import WebcamDeviceId from '@/components/WebcamDeviceId'
import WebcamCapture1 from '@/components/WebcamPro'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Camera TimeKeeping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        {/* <WebcamCapture1 /> */}
        <WebcamCapture />
        {/* <WebcamDeviceId /> */}
      </main>
    </>
  )
}
