import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { createClient } from 'contentful';

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY
  })

  const res = await client.getEntries({ content_type: "animal" })
  return {
    props: {
      animalList: res.items
    }
  }
}


export default function Home({ animalList }) {
  console.log({ animalList });
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.homeWrap}>
          <h1>Demo for call api from Contentful</h1>
          <ul>
            {
              animalList && animalList.length && animalList.map((item, index) => {
                return (
                  <li key={index} className={styles.homeWrapList}>
                    <a href={'animal/' + item.fields.slug}>{item.fields.name}</a>
                    <p>{item.fields.description}</p>
                    <figure className={styles.homeWrapImg}>
                      {
                        item.fields.picture && item.fields.picture.map((itemPic, indexPic) => {
                          return (
                            <img key={indexPic} alt={itemPic.fields.file.title} src={itemPic.fields.file.url} />
                          )
                        })
                      }
                    </figure>

                  </li>
                )
              })
            }
          </ul>
        </div>
      </main>
    </>
  )
}
